- etc/di.xml
These changes allow you to adjust the mode and debug settings per environment. For example, on production you can have the live mode and on dev the test mode. Debug mode, for example, you want to have on dev, but not on production. This is therefore environment specific.
> Type and debug config settings to .env file

- Model/Client/Orders.php
Fix for issue #99 
"When using the Orders API, it is not possible to create a creditmemo in Magento for orders that contain a shipping amount including tax."
This will fix the following error message: "Can not create online refund, as shipping costs do not match"
> Get shipping amount including tax for refunds

- Model/OrderLines.php
Path to reproduce this error:
- Set the method to *Orders API*.
- Order 2 product with both a quantity of 2, so a total cart quantity of 4.
- Create a credit memo for 3 of the 4 products.
- You get an error: 
```
Line 0 contains invalid data. An amount is required for this API call. The amount must be between €35.40 and €59.00.. Field: lines.0.amount.
```
> Bugfix: When you would refund 1 of 2 items you would get an error

- Helper/General.php
- Model/Adminhtml/Source/Method.php
- Model/Client/Payments.php
- Tests/Unit/Helper/GeneralTest.php
- etc/adminhtml/methods/bancontact.xml
- etc/adminhtml/methods/banktransfer.xml
- etc/adminhtml/methods/belfius.xml
- etc/adminhtml/methods/bitcoin.xml
- etc/adminhtml/methods/creditcard.xml
- etc/adminhtml/methods/eps.xml
- etc/adminhtml/methods/giftcard.xml
- etc/adminhtml/methods/giropay.xml
- etc/adminhtml/methods/ideal.xml
- etc/adminhtml/methods/inghomepay.xml
- etc/adminhtml/methods/kbc.xml
- etc/adminhtml/methods/klarnapaylater.xml
- etc/adminhtml/methods/klarnasliceit.xml
- etc/adminhtml/methods/paymentlink.xml
- etc/adminhtml/methods/paypal.xml
- etc/adminhtml/methods/paysafecard.xml
- etc/adminhtml/methods/sofort.xml
- etc/config.xml
This changes the description used by the payment api. The description would only contain the order number. This is now changed to `Storename: Ordernumber`. When you order in a stock Magento store the description would be something like: `Default store view: 0000025`.
Also see #112
> Put the store name in the description

- Model/Client/Orders.php
This is to allow to create shipments when the problem described in #129 occurs.
> Show a warning when the order or order line is already marked as shipped withing Mollie

- Model/Client/Orders.php
- Model/Client/Payments.php
- etc/di.xml
According to Magento technical guidelines:
> 2.5. Proxies and interceptors MUST NEVER be explicitly requested in constructors.
See: https://devdocs.magento.com/guides/v2.3/coding-standards/technical-guidelines.html
> Remove use of proxies in constructor

- Helper/General.php
- Test/Integration/Helper/GeneralTest.php
When the locale option was set to 'store', but the shop locale was not in the list of allowed locales you would get a 422 error.
- Set the configuration option `payment/mollie_general/locale` to `Store`.
- Change the language of the store view to `en_GB` (`General -> Locale Options -> Locale`)
Try to place an order. You will get this exception:
"Error executing API call (422: Unprocessable Entity): The locale is invalid. Field: locale."
> When the locale option was set to 'store', but the shop locale was not in the list of allowed locales you would get a 422 error

- Model/Client/Orders.php
- Model/Client/Payments.php
When there is invalid in one of the order or invoice emails, an exception will be thrown. As everything is handled within a transaction, this is not transaction is never finished and an error is returned to the webhook. Mollie will keep retrying for some time, and though some of the emails might keep sending.
- Create a new e-mail template and make sure this bogus code is in there:
`{{trans 'Placed on <span class="no-link">%created_at</span>' created_at=$order.BigFatError(2) |raw}}`
- Configure it to be used (Config -> Sales -> Sales Emails).
- Place an …
> Catch error when sending emails. This prevents that multiple emails are being sent

- Helper/General.php
- Model/Client/Payments.php
- Test/Unit/Helper/GeneralTest.php
> Execute the $order->cancel() method so the `sales_order_payment_cancel` event is thrown

- Model/OrderLines.php
- Test/Integration/Model/OrderLinesTest.php
> Bugfix: There is always an orderLine object returned, but it can be empty when no records found

- Helper/General.php
- Model/Client/Payments.php
- Test/Unit/Helper/GeneralTest.php
> Bugfix: The correct store name is now used when using the {storename} variable in the payment description

- Helper/General.php
- Model/Client/Orders.php
- Model/Client/Payments.php
> Fix: Use the correct pending payment status for banktransfer

- GraphQL/Resolver/Cart/AvailableIssuersForMethod.php
- Model/Mollie.php
- Service/Mollie/GetIssuers.php
*Frontend*
*Backend*
**Other**
When i...
> Bugfix: The graphql query 'mollie_available_issuers' would throw an error

- Setup/UpgradeSchema.php
The comment for the column mollie_customer_id in the table mollie_payment_customer was wrong. I fixed it.
*Frontend*
*Backend*
**Other**
When i...
> Fixed Comment in DB Schema

- Api/Webapi/GetCustomerOrderInterface.php
- Api/Webapi/StartTransactionRequestInterface.php
- Test/Integration/Webapi/AbstractWebApiTest.php
- Test/Integration/Webapi/GetCustomerOrderTest.php
- Test/Integration/Webapi/PaymentTokenTest.php
- Test/Integration/Webapi/StartTransactionTest.php
- Webapi/GetCustomerOrder.php
- Webapi/PaymentToken.php
- Webapi/StartTransaction.php
*Frontend*
*Backend*
**Other**
Open this URL, it fails:
```
{{URL}}/default/rest/all/schema?services=all
```
> Bugfix: Add a valid rest api schema

- Config.php
- Test/Integration/Controller/Checkout/SecondChanceTest.php
*Frontend*
*Backend*
When 'Enable second chance email' is disabled, but 'Automatically send second chance emails' is still enabled via the Magento 2 admin (an input mistake that is easily made by the store manager), reminder emails are still being send via cron.
Check `\Mollie\Payment\Test\Integration\Controller\Checkout\SecondChanceTest::testSecondChanceDisabledAutoSendEnabled`
> Fix second chance disabled setting

- Service/Mollie/GetIssuers.php
*Frontend*
*Backend*
**Other**
Cache identifier used for all storeview were the same.
So a dutch storeview could get a german translated string if this was the last thing cached.
This fix adds the localcode to the cache identifier, providing unique cache per storeview. 
1. Have a Multi-language store 
2. Go to German store view
3. add product to cart
4. Go …
> Bugfix: Add localecode to cache_indentifier

- view/frontend/web/js/view/payment/method-renderer/default.js
*Frontend*
*Backend*
**Other**
We encountered a problem in the Mollie module which causes the following issue: 
https://github.com/danslo/CleanCheckout/issues/91#issuecomment-757833549
The clean checkout module uses the afterPlaceOrder method. Mollie breaks that functionality currently. 
Open the environment and place a console.log or debugger in the magento/module-checkout/view/frontend/web/js/view/payment/default.js file in the afterPlaceOrder method. This now gets called as well as the Mollie …
> compatible: afterPlaceOrder super gets called so other modules can use the function

- Observer/MollieProcessTransactionEnd/RemoveCompletedOrdersFromPendingPaymentTable.php
- Observer/SalesOrderPlaceBefore/RemovePendingPaymentReminders.php
- Service/Order/DeletePaymentReminder.php
- Service/Order/PaymentReminder.php
*Frontend*
*Backend*
**Other**
* Pyament Reminder
When you place an order the event "sales_order_place_before" is triggered an the method `\Mollie\Payment\Observer\SalesOrderPlaceBefore\RemovePendingPaymentReminders::execute` is being executed. This method wants to delete all payment reminders by email. The email address is fetched from the order and sent to `\Mollie\Payment\Service\Order\DeletePaymentReminder`. There we create a new order collection based on the filters `CREATED_AT` and `CUSTOMER_EMAIL`. Now you're retrieving all the orders with that email address regardless of the customer id (so you will get …
> Delete Payment Reminders for guest users by email and for loggedin by customer id

- Config.php
*Frontend*
*Backend*
**Other**
When i...
> Fix PHP 8.1 error in str_replace

- Service/Order/Lines/Generator/FoomanTotals.php
- etc/di.xml
*Frontend*
*Backend*
**Other**
This PR fixes the issue https://github.com/mollie/magento2/issues/512 we had when customers were trying to checkout with Klarna Pay Later or Klarna Slice It and had a Fooman Order Fee applied. All credits to @fooman for creating this patch.
Open the environment and a custom option added by the Fooman Order Fees module. …
> Add compatibility for Fooman Order Fees

- view/frontend/web/js/model/payment-token.js
- view/frontend/web/js/view/payment/method-renderer/default.js
**This PR touches code in the following areas:**
*Frontend*
- Install Magento 2.4.4 with latest mollie payment module
- Try placing an order (eg with iDEAL)
- Exception: `promise.success is not a function`
Magento 2.4.4 upgraded jQuery to 3.6, removing the deprecated `success` function on the jqXHR response. `done` should be used in `payment-token.js`
- Try placing an order (eg with iDEAL)
- You should be redirected to bank
> Replace `success` with `done` function for jQuery 3.6 in M2.4.4

- Service/Order/Uncancel/OrderReservation.php
Using ObjectManager directly causes exceptions in the objectmanager while uncanceling orders.
Using ObjectManagerInterface instead fixes all of these problems, in the rest of this project the interface is already used.
*Frontend*
*Backend*
**Other**
When updating the order status of a canceled order with payment method Sepa Bank Transfer which has been paid an exception will be thrown …
> Utilise ObjectManagerInterface instead of ObjectManager

- view/frontend/web/js/view/checkout/save-payment-method.js
This fix adds compatibility to jQuery 3.0. `error()` has been removed since jQuery 3.0. Since Magento 2.4.4 uses jQuery 3.0, this should be changed.
**jQuery post documentation:**
https://api.jquery.com/jquery.post/
**Magento's jQuery version file:**
https://github.com/magento/magento2/blob/2.4.4/lib/web/jquery/jquery.min.js
> jQuery 3.0.x compatibility

- Controller/Checkout/Webhook.php
This PR touches code in the Webhook.
When the webhook is called with an ID which is not in the backend, it returns a 404 HTTP status code. This reveals that the ID of that transaction does not belong to the merchant. As stated in the [Mollie docs](https://docs.mollie.com/overview/webhooks):
"To not leak any information to malicious third parties, it is recommended to return a 200 OK response even if the ID is not known to your system."
Because of this, I have deleted the lines of code which returns anything but a 200 OK response, and instead used the method getOkResponse() to return a 200 OK, on transactions and orders which are not found in the backend. Checked a few other integrations and they seem to do this properly (always return 200 OK).
Once …
> Return 200 OK on IDs not known in the system

- Service/Order/Lines/Order.php
*Frontend*
*Backend*
**Other**
Fix for #590 
When i...
> check if Order item is virtual instead of check order item product type

- Plugin/Tax/Helper/Data.php
*Frontend*
*Backend*
**Other**
When i...
> Check if the Payment Fee is available before calculating

- Controller/ApplePay/ShippingMethods.php
- [] Contains tests for the changed/added code (great if so but not required).
*Frontend*
*Backend*
Resolve issue where changing shipping method in ApplePay does not correctly update the quote, resulting in orders failing.
Simplify entire code to remove unrequired saves/collects that are adding to the problem.
Don't set a default shipping method - by the nature of this method a shipping method is always being passed in.
When I change delivery method within Apple Pay popup, it should show a new total in the window including the new shipping amount. Currently the total doesn't update. Apple Pay then authorises the …
> Resolve delivery methods issue on Apple Pay

- view/frontend/web/js/view/payment/method-renderer/applepay-direct.js
*Frontend*
*Backend*
When loading the payment methods on Safari or Apple Devices, when Apple Pay is enabled the following error may occur:
```
this.applePayPaymentToken() is not a function
```
Attached screenshot from Safari DevTools:
When this occurs it blocks all Mollie Payment methods from being rendered, including Credit Cards. This problem occurs due to this.applePayPaymentToken() not being defined as an observable in the component's defaults on load.
1. Open environment on a Safari or Apple device supporting Apple Pay
2. Add product, go to checkout
3. Apple Pay should display
> BUGFIX - Fix issue where this.applePayPaymentToken may not be defined at checkout

- Controller/Checkout/Process.php
- [ x] The code is working on a plain Magento 2 installation.
- [x ] The code follows the PSR-2 code style.
*Frontend*
- [x ] Shopping cart
- [ x] Checkout
*Backend*
- [ x] Creating the order
**Other**
When customer goes to mollie side, select bankcontract and in test mode select "FAILED" status, press continue - redirect goes to magento and restore not the latest quote but one before …
> [DOK-138] handle failed status

- etc/adminhtml/system.xml
Replacing the current admin window and causing unsaved changes to be lost is not a great experience.
---
*Frontend*
*Backend*
**Other**
When I click on the `Mollie Profile` link in the API configuration group, the browser navigates to the Mollie dashboard - causing any unsaved configuration changes to be lost, which can be annoying.
1. Log into the admin …
> Open Mollie Dashboard in New Tab

- .github/workflows/end-2-end-test.yml
- .github/workflows/templates/docker-compose.yml
- .github/workflows/templates/magento/configure-mollie.sh
- Test/End-2-end/cypress.config.js
- Test/End-2-end/cypress/e2e/magento/no-api-key.cy.js
*Frontend*
*Backend*
**Other**
When i...
> PIMAG-686 | Improvement: Add test scenario for when the API key is not set #829

- Controller/Checkout/Process.php
- Service/Mollie/Order/AddResultMessage.php
- i18n/de_DE.csv
- i18n/en_US.csv
- i18n/es_ES.csv
- i18n/fr_FR.csv
- i18n/it_IT.csv
- i18n/nl_NL.csv
*Frontend*
*Backend*
**Other**
When i...
> PIMAG-714 | Improvement: Improved message when transaction fails

- Service/Order/TransactionPart/LimitStreetLength.php
- Test/Integration/Service/Order/TransactionPart/LimitStreetLengthTest.php
*Frontend*
*Backend*
**Other**
When i...
> PIMAG-750 | Bugfix: Check if the shipping address isset #841

- Test/End-2-end/cypress/support/e2e.js
- Test/End-2-end/cypress/support/pages/backend/OrdersPage.js
*Frontend*
*Backend*
**Other**
When i...
> PIMAG-746 | Improvement: Add retry mechanism for Cypress to handle async webhooks

- Observer/LockUnlockOrder.php
- Service/LockService.php
- etc/events.xml
*Frontend*
*Backend*
**Other**
When i...
> PIMAG-747 | Bugfix: Prevent race conditions when saving shipment trackings

- Service/Order/CancelOrder.php
I did not test it, but came across it, so this should be handled by magento in this plugin:
vendor/magento/module-sales-rule/etc/di.xml
```
<type name="Magento\Sales\Model\Service\OrderService">
<plugin name="coupon_uses_decrement_plugin" type="Magento\SalesRule\Plugin\CouponUsagesDecrement" />
</type>
```
It's probably not a big deal, but it can affect the coupon_usages number if it is applied twice.
Actually, the plugin has been in Magento for quite a while. I checked the merge request that added this functionality in Mollie, and it was from 2018. Magento later fixed it: [GitHub Issue #12817](https://github.com/magento/magento2/issues/12817). That's probably why it's still in the code.
> remove resetCouponAfterCancellation because it's handled by CouponUsagesDecrement plugin

- Webapi/PaymentInformationMeta.php
- [x ] The code is working on a plain Magento 2 installation.
- [ x] The code follows the PSR-2 code style.
- [ na] When an exception or error is logged the message is accompanied with some context, eg: `Error when trying to get the payment status:`
- [ na] Contains tests for the changed/added code (great if so but not required).
- [ na] I have added a scenario to test my changes.
*Frontend*
- [ x] Payment methods
*Backend*
**Other**
**Please …
> PIMAG-826 | Add missing API client to function call arguments.

- Observer/SalesModelServiceQuoteSubmitSuccess/StartTransactionForPointOfSaleOrders.php
- etc/events.xml
*Frontend*
*Backend*
**Other**
When i...
> [PIMAG-786] Bugfix: Call startTransaction for backend point of sale orders #888

- Service/Order/PaymentReminder.php
*Frontend*
*Backend*
**Other**
Second Chance Email
The following cronjob failed:
Job	mollie_send_pending_payment_reminders
Messages	Error when running a cron job: Call to a member function isSaleable() on null
Executed at	2025-05-02 09:00:09
1. Configure second chance email.
2. Cancel order payment.
3. Delete ordered product.
4. Wait for second chance email cronjob.
5. Observe above error.
> PIMAG-786 | Fix Cron Error When Product Has Been Deleted

- Model/Client/Orders.php
- Service/Order/TransactionPart/LimitedMethods.php
- Test/Integration/Service/Order/TransactionPart/LimitedMethodsTest.php
- etc/di.xml
*Frontend*
*Backend*
**Other**
When i...
> [PIMAG-691] Bugfix: Limit methods for Payments API too

- Model/Client/Orders.php
- Service/Order/TransactionPart/LimitedMethods.php
- Test/Integration/Service/Order/TransactionPart/LimitedMethodsTest.php
- etc/di.xml
*Frontend*
*Backend*
**Other**
When i...
> Bugfix: Limit methods for Payments API too

- Block/Adminhtml/Widget/Grid/PaypalReferenceColumn.php
- Block/Info/Base.php
- Config.php
- etc/adminhtml/methods/paypal.xml
- etc/config.xml
- view/adminhtml/layout/sales_transactions_grid_block.xml
- view/adminhtml/templates/info/mollie_base.phtml
*Frontend*
*Backend*
**Other**
When i...
> Bugfix: Verify that details is a JSON string

- Block/Adminhtml/Widget/Grid/PaypalReferenceColumn.php
CLI `bin/magento setup:di:compile` will create the Interceptor, but Magento throws an exception when generating it on-the-fly (in Developer mode).
See issue #937
> Fix: Magento can't handle the 'self' argument type
