etc/di.xml
See https://github.com/mollie/magento2/issues/84
=> Added Test an d Live keys to dotenv.

view/frontend/web/template/payment/giftcard.html, view/frontend/web/template/payment/ideal.html, view/frontend/web/template/payment/kbc.html
=> Make the logo & name in the issuer list clickable

Model/Client/Orders.php, Test/Integration/Model/Client/OrdersTest.php
See https://github.com/mollie/magento2/issues/135#issuecomment-499878370
=> Add the entity id of the order number to the log when it is not possible to cancel an order

Model/Client/Orders.php
=> Bugfix: When sending the full order the invoice email would not be send

Helper/General.php, Test/Unit/Helper/GeneralTest.php
=> Bugfix: A canceled order would result in an exception

Setup/UpgradeData.php
=> Check the active flag on every upgrade

Config.php, Helper/General.php, Model/Adminhtml/Source/NewStatus.php, Model/Methods/Paymentlink.php, Model/Mollie.php, Test/Integration/Model/Methods/PaymentlinkTest.php, etc/adminhtml/methods/paymentlink.xml
=> Feature: You can set a custom status for paymentlink orders

Service/Order/ProcessAdjustmentFee.php, Test/Unit/Service/Order/ProcessAdjustmentFeeTest.php
=> When doing a partial refund the amount was based on the total order

view/frontend/web/js/view/checkout/summary/payment-fee.js
=> Bugfix: IE11 doesn't understand ES6

Plugin/Email/Model/Template/Config.php
=> Bugfix: Sometimes the wrong email path was generated

view/frontend/web/js/view/checkout/save-payment-method.js
=> Bugfix: Check if the checkout agreements config ise available

Config.php, GraphQL/Resolver/Cart/AvailableIssuersForMethod.php, Model/Mollie.php, Model/MollieConfigProvider.php, Model/PaymentFee/Quote/Address/Total/PaymentFeeTax.php, Service/Config/PaymentFee.php, Service/Mollie/GetIssuers.php, Service/PaymentFee/Types/Percentage.php, etc/adminhtml/methods/applepay.xml, etc/adminhtml/system.xml, etc/config.xml, etc/sales.xml
*Frontend*
*Backend*
**Other**
When i...
=> Release week 28

Config.php, Setup/UpgradeData.php, etc/module.xml
*Frontend*
*Backend*
**Other**
When i...
=> Bugfix: Update the correct scope

etc/webapi.xml
Fixes: https://github.com/mollie/magento2/issues/318
=> Made it possible to start a transaction as guest

.github/workflows/end-2-end-test.yml, Model/Client/Payments.php, Model/Mollie.php, Observer/SalesOrderShipmentSaveBefore/CreateMollieShipment.php, Service/Mollie/Order/CreateInvoiceOnShipment.php
See #669 for more information.
=> Bugfix: Handle the new transaction ID for orders

view/frontend/web/template/payment/giftcard.html
=> NTR: Correct selection string for giftcard

Model/Adminhtml/Backend/ChangeApiMode.php
*Frontend*
*Backend*
**Other**
When i...
=> Bugfix: Check that the api key is available #752

Webapi/StartTransaction.php
*Frontend*
*Backend*
**Other**
As Apple Pay does not have a hosted page to redirect to, Mollie will return `null` in the `checkoutUrl`.
Since the order is immediately paid in such cases, it is expected to redirect to the configured `redirectUrl`.
When I start a transaction with Apple Pay, the endpoint does not return a URL, resulting in the frontend not having the ability to redirect to the order confirmation by themselves, as relevant details that are normally in the …
=> Added RestAPI compatibility with methods such as Apple Pay

Service/Mollie/SelfTests/AreHyvaModulesInstalled.php, Service/Mollie/SelfTests/IsHyvaThemesJsonCorrect.php, etc/adminhtml/di.xml
*Frontend*
*Backend*
**Other**
When i...
=> PIMAG-748 | Improvement: Add checks for Hyvä to the self tests

Model/Adminhtml/Source/CustomerGroup.php, Service/Mollie/PointOfSaleAvailability.php, Test/Integration/Service/Mollie/PointOfSaleAvailabilityTest.php
*Frontend*
*Backend*
**Other**
When i...
=> PIMAG-751 | Feature: Allow POS access for guests #823

Model/Methods/Reorder.php, Model/Methods/Voucher.php, Model/Mollie.php, Service/Mollie/LogException.php, Test/Fakes/ConfigFake.php, Test/Integration/Service/Mollie/LogExceptionTest.php
*Frontend*
*Backend*
**Other**
When i...
=> PIMAG-749 | Improvement: Do not log validation error #839

Model/Client/Payments.php
*Frontend*
*Backend*
**Other**
When i...
=> PIMAG-745 | Improvement: Move billingEmail to billingAddress.email

Block/Product/View/ApplePay.php, Controller/ApplePay/BuyNowValidation.php, Controller/Checkout/ApplePayValidation.php, Observer/ShortcutButtonsContainer/AddApplePayShortcutButton.php, Service/Mollie/ApplePay/Validation.php
*Frontend*
*Backend*
**Other**
When i...
=> [PIMAG-781] Feature: Add test mode support for Apple Pay

Config.php, Service/Config/PaymentFee.php, Service/PaymentFee/Types/Percentage.php, Test/Integration/Service/PaymentFee/Types/PercentageTest.php, etc/adminhtml/system.xml
*Frontend*
*Backend*
**Other**
When i...
=> [PIMAG-783] Improvement: Optionally include discount in surcharge calculation #884

Service/Order/Lines/Order.php
*Frontend*
*Backend*
**Other**
When i...
=> [PIMAG-782] Bugfix: Round totals before adjustment calculation

Service/Quote/QuoteHasMealVoucherProducts.php
*Frontend*
*Backend*
**Other**
When i...
=> PIMAG-787 | Bugfix: Do not show voucher for mixed carts #891

Api/TransactionToOrderManagementInterface.php, Model/Client/Orders/ProcessTransaction.php, Model/Client/Payments.php, Model/TransactionToOrderManagement.php, Service/Mollie/Order/GetTransactionId.php, Test/Fakes/Model/Client/Orders/ProcessTransactionFake.php, Test/Fakes/Service/Mollie/FakeMolliePaymentApiEndpoint.php, Test/Integration/Service/Mollie/Order/GetTransactionIdTest.php, etc/di.xml
*Frontend*
*Backend*
**Other**
When i...
=> Bugfix: Prevent paid order from being canceled #903

GraphQL/Resolver/Cart/AvailableTerminalsForMethod.php, Observer/SalesModelServiceQuoteSubmitSuccess/StartTransactionForPointOfSaleOrders.php, Test/End-2-end/cypress/e2e/magento/api/graphql-place-order.cy.js, Test/End-2-end/cypress/e2e/magento/api/rest-place-order.cy.js, Test/End-2-end/cypress/fixtures/mollie-pwa-graphql.html, Test/End-2-end/cypress/fixtures/mollie-pwa-rest.html, etc/events.xml
*Frontend*
*Backend*
**Other**
When i...
=> Bugfix: Call startTransaction for backend point of sale orders

Model/MollieConfigProvider.php, Service/Mollie/GetIssuers.php, Webapi/PaymentInformationMeta.php
*Frontend*
*Backend*
**Other**
When i...
=> PIMAG-824 | Improvement: Remove unused parameter #887

Service/Quote/QuoteHasMealVoucherProducts.php
*Frontend*
*Backend*
**Other**
When i...
=> Bugfix: Do not show voucher for mixed carts #891

etc/config.xml
*Frontend*
*Backend*
**Other**
When i...
=> PIMAG-822 | Improvement: Klarna default countries #890

Model/Client/Payments.php
*Frontend*
*Backend*
**Other**
When i...
=> PIMAG-821 | Improvement: Add email to address

Api/TransactionToOrderManagementInterface.php, Model/Client/Orders/ProcessTransaction.php, Model/Client/Payments.php, Model/TransactionToOrderManagement.php, Service/Mollie/Order/GetTransactionId.php, Test/Fakes/Model/Client/Orders/ProcessTransactionFake.php, Test/Fakes/Service/Mollie/FakeMolliePaymentApiEndpoint.php, Test/Integration/Service/Mollie/Order/GetTransactionIdTest.php, etc/di.xml
*Frontend*
*Backend*
**Other**
When i...
=> PIMAG-825 | Bugfix: Prevent paid order from being canceled #903

Config.php, Service/Config/PaymentFee.php, Service/PaymentFee/Types/Percentage.php, Test/Integration/Service/PaymentFee/Types/PercentageTest.php, etc/adminhtml/system.xml
*Frontend*
*Backend*
**Other**
When i...
=> PIMAG-823 | Improvement: Optionally include discount in surcharge calculation #884

Service/Order/Lines/Order.php
*Frontend*
*Backend*
**Other**
When i...
=> PIMAG-820 | Bugfix: Round totals before adjustment calculation

Controller/ApplePay/PlaceOrder.php, Controller/ApplePay/ShippingMethods.php
*Frontend*
*Backend*
**Other**
When i...
=> PIMAG-766 | Improvement: Force the country code to be uppercase
